### ISSUE TITLE
safelink

### ISSUE THREAD

**Issue by KagaKouko99** [Hakame-kun/uBlock-Filters-Indonesia#12]
http://www.zahela.com/2019/08/uchuu-senkan-tiramisu-sub-indo-360p.html

http://safelinku.com/fullpage/script.js

**Comment by Hakame-kun** [comment]
<a href="https://imgur.com/yqNOUQE"><img src="https://i.imgur.com/yqNOUQE.png" title="source: imgur.com" /></a>
Seharusnya sudah otomatis kalau pakai filters default, ignore generic cosmetic filtersnya di uncheck ya
<a href="https://imgur.com/tYbXzca"><img src="https://i.imgur.com/tYbXzca.png" title="source: imgur.com" /></a>

**Comment by KagaKouko99** [comment]
iya salah kirain itu script 3d party buat safelinku

**Comment by Hakame-kun** [comment]
> iya salah kirain itu script 3d party buat safelinku
> btw itu yg dan pollock hp host ama mvos host buat blokir apa tracking bukan?

Sesuai judulnya gan, multipurpose (kegunaannya bermacam)
