### ISSUE TITLE
jossbingit.xyz

### ISSUE THREAD

**Issue by KagaKouko99** [Hakame-kun/uBlock-Filters-Indonesia#16]
https://moviegan.com/movies/avengers-endgame-2019/
https://filmgan.pw/avengers-endgame/

https://jossbingit.xyz/wp-content/plugins/soralink/assets/js/soralink.js

**Comment by Hakame-kun** [comment]
<a href="https://imgur.com/x069OmX"><img src="https://i.imgur.com/x069OmX.png" title="source: imgur.com" /></a>
Silahkan dicek lagi gan, udah diboost timer closetopicnya, contentnya sudah dihide biar mempermudah
