### ISSUE TITLE
Blocking continue link

### ISSUE THREAD

**Issue by KagaKouko99** [Hakame-kun/uBlock-Filters-Indonesia#18]
https://loot.vozdesportiva.com/2019/05/disability-insurance.html?url=IyNMTiUxRSUxQiUxQiUwN0VHSyUwNlElNURDTSU1QyU1QklYJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
https://loot.vozdesportiva.com/2019/05/disability-insurance.html?url=IyNMTiUxRSUxQiUxQiUwN0VHSyUwNlElNURDTSU1QyU1QklYJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj

**Comment by Hakame-kun** [comment]
<img src="https://i.imgur.com/2Q1W2LF.png" />
Sudah gan
