### ISSUE TITLE
boost countdown

### ISSUE THREAD

**Issue by KagaKouko99** [Hakame-kun/uBlock-Filters-Indonesia#19]
gan kira" bisa ga adsafelink yg baru ini di boost countdownnya btw saya ga ngerti itu countdownya client side atau server side
https://pastebin.com/B0WQqNi0

**Comment by Hakame-kun** [comment]
Untuk masalah countdown bisa jadi client atau pun server. Kalau yang server biasanya safelink dengan high rates payout dan setelah dicoba pakai namaweb.com##+js(nano-setInterval-booster.js) muncul tulisan (Bad Request) [Bisa dicoba, masukkan saja di My filters. Ente coba sendiri 👍] . Shortlink buatan sendiri masih bisa dibypass biasanya gan dan bisa langsung ke link yang dituju

**Comment by KagaKouko99** [comment]
@Hakame-kun gan bisa ga mengetahui domain apa saja yg dipke ?
contoh https://adsafelink.net/Bj86qc3p kadang selalu diarahkan otomatis acak ke domain lainya
https://liputannubi.net/mobil-teraneh-di-dunia/
https://wadooo.com/2018/01/02/berinvestasi-dalam-diri-anda-3-alasan-terbaik-untuk-berinvestasi-dalam-diri-anda-sendiri/#i5MQGyY

trus kayak https://autoratio.com/J0wI9G3 
dialih kan acak ke lewat.club www.adlink.pw safe.mirrordown kabarviral dll

**Comment by Hakame-kun** [comment]
Domain wadooo.com sudah ya.. Nanti kalau sudah ganti domain bisa langsung comment saja gan

**Comment by KagaKouko99** [comment]
@Hakame-kun 
https://liputannubi.net/g/QpvRF095iS
https://pantauterus.me/g/QpvRF095iS
https://bercara.com/kc8wLuEh51J
http://semawur.com/vHiX
http://in11.site/v7CuUpYM

klo filter buat ngilangin fokus gmn gan seperti timer di safelink yg server side pas kita buka tab lain lain timernya ga jalan

sama 1 lg gan mw nnya kira" safelink yg ini bisa dibypass ga
https://github.com/timmyRS/Universal-Bypass/issues
issue 193 komenan bawah sndiri gan thanks

**Comment by Hakame-kun** [comment]
@KagaKouko99. Ane kurang tau maksud ente tapi kyk gini bukan ? Dihilangkan, hanya perlu melewati verifynya saja ?
**Liputannubi:**
![image](https://user-images.githubusercontent.com/37291660/64476603-b5755a80-d1ba-11e9-8f39-b67f964d7cac.png)
**Pantauterus:**
![image](https://user-images.githubusercontent.com/37291660/64476596-9d054000-d1ba-11e9-8d99-b6fd4a449cb8.png)
**Gotravelgo:**
![image](https://user-images.githubusercontent.com/37291660/64476630-37658380-d1bb-11e9-8c8b-370c9215fbc8.png)
**Bercara:** 
![image](https://user-images.githubusercontent.com/37291660/64476659-e2763d00-d1bb-11e9-9535-79cf2f2eb9f4.png)
**Semawur:**
![image](https://user-images.githubusercontent.com/37291660/64476662-f91c9400-d1bb-11e9-94e3-25c5be0905a3.png)
**In11site**
![image](https://user-images.githubusercontent.com/37291660/64476689-7942f980-d1bc-11e9-971b-15c40c44a095.png)
**rufafs.me**
![image](https://user-images.githubusercontent.com/37291660/64476696-92e44100-d1bc-11e9-8684-51a24b646a07.png)
![image](https://user-images.githubusercontent.com/37291660/64476700-9f689980-d1bc-11e9-94fb-c249e6940415.png)

**Comment by Hakame-kun** [comment]
Hmm, next request ulang aja ya gan.. Panjang ke bawah kurang enak juga hehe

**Comment by KagaKouko99** [comment]
@Hakame-kun maksud ane yg fokus itu seperti ini `https://github.com/uBlockOrigin/uAssets/issues/6254`

klo yg bypass itu ya langsung auto ketujuan link ga pake ngisi captcha ngeklik dan segala macamnya

**Comment by Hakame-kun** [comment]
> @Hakame-kun maksud ane yg fokus itu seperti ini `https://github.com/uBlockOrigin/uAssets/issues/6254`
> 
> klo yg bypass itu ya langsung auto ketujuan link ga pake ngisi captcha ngeklik dan segala macamnya

Seharusnya sekarang sudah bisa yang fokus ##+js(set-constant, blurred, false). Untuk captcha lum bisa gan
