### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by RaveN0X87** [Hakame-kun/uBlock-Filters-Indonesia#2]
di safelink https://wegner.tech/PDGh trus safelinku pake filter ublock ID bisa langsung auto ke destinasi link
klo untuk safelink lain bisa ga 
seperti :
https://adsafelink.net/hPkDqX
https://adsafelink.net/g6FGEI
https://autoratio.com/4aKmw1Gjzd
https://kabarviral.blog/post/top-android-phone-games?4aKmw1Gjzd=1&d=1
https://tips.atv.pw/post/top-android-phone-games?6gZp3Z=1&d=0
https://hokiciki.org/vb9VD
https://linkduit.net/LurlH

makasih

**Comment by Hakame-kun** [comment]
Wegner, adsafelink, kabarviral, lewat.club  tidak bisa ya, server-sided (akan terkena bad request).
Hokiciki dan linkduit sudah ditambahkan : hokiciki.org##+js(nano-setInterval-booster.js) & linkduit.net##+js(nano-setInterval-booster.js)
