### ISSUE TITLE
safelinku generate linknya hilang

### ISSUE THREAD

**Issue by KagaKouko99** [Hakame-kun/uBlock-Filters-Indonesia#21]
https://bercara.com/EVvEq6in1QG
https://bercara.com/KaxepOOk

klo menurut saya filter yg buat ngilangin teks diblog safelink dll mnding ga usah gan. cukup iklan popup anti adblock fake download button auto fokus boost timer aja yg pnting seperti ublock filter. karena klo diilangin smua kadang mempengaruhi script" bypass shorteners seperti adsbypasser
![Annotation 2019-09-08 105025](https://user-images.githubusercontent.com/54178411/64483062-b5ab3f80-d226-11e9-9ab2-6a4858eda577.png)

**Comment by KagaKouko99** [comment]
yg ini juga blank
https://lewat.club/post/top-android-phone-games?hOFwITu=1&d=1
https://www.adlink.pw/post/top-android-phone-games?0KMyeycvD=1&d=0

**Comment by Hakame-kun** [comment]
00593b6 Udah diremove gan, thanks feedbacknya

**Comment by KagaKouko99** [comment]
@Hakame-kun saran gan klo misal nambahin safelink" baru cukup filter buat ads/banner ads, popup,fake download button,anti adblock,trackers,out of focus countdown,boost countdown klo yg bukan server side. yg lainya biarin default gan.
