### ISSUE TITLE
Anti adblock

### ISSUE THREAD

**Issue by RaveN0X87** [Hakame-kun/uBlock-Filters-Indonesia#24]
https://claimbits.net/shortlinks.html
https://clickbits.io/shortlinks.html
https://bitsfree.net/shortlinks.html
https://click4bits.com/?page=shortlinks

**Comment by Hakame-kun** [comment]
> @Hakame-kun btw nanya gan yg filter diublock origin default region listnya kok bukan ini gan kok malah ABPindo

Mungkin karena ABPindo itu terbagi-bagi filtersnya.. Dan mereka sudah lama bekerjanya (kontributornya juga ada 10an 😄 ) dari tahun 2013 kalau tidak salah

**Comment by Hakame-kun** [comment]
> @Hakame-kun btw nanya gan yg filter diublock origin default region listnya kok bukan ini gan kok malah ABPindo

Mungkin karena ABPindo itu terbagi-bagi filtersnya.. Dan mereka sudah lama bekerjanya (kontributornya juga ada 10an 😄 ) dari tahun 2013 kalau tidak salah
