### ISSUE TITLE
Anti adblock

### ISSUE THREAD

**Issue by RaveN0X87** [Hakame-kun/uBlock-Filters-Indonesia#25]
https://bitsroll.com/shortlinks.html
https://moremoney.io/?page=shortlinks
https://winbitcoin.io/shortlinks.html
https://www.blitzcoiner.com/?page=shortlinks
https://doge-bitsfree.net/shortlinks.html

**Comment by Hakame-kun** [comment]
a9008be dicoba lagi ya gan

**Comment by RaveN0X87** [comment]
@Hakame-kun kenapa ngga request gan coba biar filter ini dimasukin ke ublock origin region default 
contohnya kayak china italia jepang korea Polandia Rusia spanyol filter default region listnya lebih dari 1.
dan nanti klo misal banyak user yg make filternya jg pasti ada kontributor lain yg mau bantu. klo sedikit yg make ya yg punya repo aja pling yg mau maintenance.

**Comment by Hakame-kun** [comment]
@RaveN0X87 Kalau untuk request sih sebenarnya sudah masuk ya https://filterlists.com/lists/ublock-indo
Mungkin karena user lebih sering menggunakan ABP (AdBlock Plus) daripada uBlock, jadi kurang mengerti fungsinya.. Padahal kalau saya bandingkan lebih enak pakai uBlock 😆 Penggunaan resource Windows di Chrome lebih kecil. Dan juga uBlock banyak script. Bisa focus di safelink (stay, padahal lagi buka tab lain), boost time countdown, dll

**Comment by RaveN0X87** [comment]
@Hakame-kun bukan di filterlist,com request ke owner ublock origin gorhill biar dimasukin ke default region filter list di UBo
