### ISSUE TITLE
Bug kazefuri.me

### ISSUE THREAD

**Issue by WaferNabati** [Hakame-kun/uBlock-Filters-Indonesia#29]
banyak filter ublock indo yg membuat safelink jd seperti gmbar dibawah
![Annotation 2019-09-20 203816](https://user-images.githubusercontent.com/9379770/65331330-cd030900-dbe6-11e9-9bd6-a484959d07bb.png)

https://kazefuri.web.id/a-portrait-of-jianghu-bu-liang-ren-ep-05-subtitle-indonesa/

**Comment by Hakame-kun** [comment]
🏷 a87db3c `Fixed`
![image](https://user-images.githubusercontent.com/37291660/65342749-92f13180-dbfd-11e9-9dbf-e6a879797322.png)

**Comment by Hakame-kun** [comment]
> banyak filter ublock indo yg membuat safelink jd seperti gmbar dibawah
> ![Annotation 2019-09-20 203816](https://user-images.githubusercontent.com/9379770/65331330-cd030900-dbe6-11e9-9bd6-a484959d07bb.png)
> 
> https://kazefuri.web.id/a-portrait-of-jianghu-bu-liang-ren-ep-05-subtitle-indonesa/

Tujuannya sih, supaya pengguna lebih cepat untuk mengakses link yang dibutuhkan. Jadi tidak perlu melihat isi (post) di dalam shortlinknya

**Comment by WaferNabati** [comment]
@Hakame-kun Klo mw cpt mnding pke ini gan 
https://pastebin.com/vvuEFybk

**Comment by Hakame-kun** [comment]
> @Hakame-kun Klo mw cpt mnding pke ini gan
> https://pastebin.com/vvuEFybk

Sudah beda ekstensi gan. Mungkin nanti akan dibuat sama developernya JS/+js(namascript) untuk bypass link yang seperti itu.
