### ISSUE TITLE
Bug bagilagi terdeteksi

### ISSUE THREAD

**Issue by RaveN0X87** [Hakame-kun/uBlock-Filters-Indonesia#3]
https://drivenime.com/cannon-busters-subtitle-indonesia-batch/

klo filter ublock indo diaktifkan safelink akan dialihkan ke safelink lain tidak ke destinasi tujuan
tolong di fix

**Comment by Hakame-kun** [comment]
Fixed. Silahkan diupdate dan dicoba lagi
