### ISSUE TITLE
Bug safelinku

### ISSUE THREAD

**Issue by Arsindy** [Hakame-kun/uBlock-Filters-Indonesia#30]
https://kazefuri.web.id/incarnation-eps-5/

**Comment by Hakame-kun** [comment]
Bugnya dimana ya ? Sudah dicek ulang, aman kok

**Comment by Arsindy** [comment]
@Hakame-kun uda gw tes filter lain ga ada masalah ini gegara filter ublock id generate linknya jadi hilang
![Annotation 2019-09-23 084656](https://user-images.githubusercontent.com/55402429/65398034-ec648680-ddde-11e9-951d-715c7dd5dbc0.png)

**Comment by Hakame-kun** [comment]
> @Hakame-kun uda gw tes filter lain ga ada masalah ini gegara filter ublock id generate linknya jadi hilang
> ![Annotation 2019-09-23 084656](https://user-images.githubusercontent.com/55402429/65398034-ec648680-ddde-11e9-951d-715c7dd5dbc0.png)

Sudah diupdate manual gan ? #21 Masalahnya sudah lama difix kok
![image](https://user-images.githubusercontent.com/37291660/65404300-2e52f400-de02-11e9-8431-2f5051af5f38.png)

**Comment by Hakame-kun** [comment]
Sehari lebih tidak ada jawaban saya anggap sudah tidak bermasalah ya

**Comment by ravendinata** [comment]
Link tidak muncul lagi meskipun adblock sudah dimatikan
