### ISSUE TITLE
bitlinks.pw anti-adblock

### ISSUE THREAD

**Issue by arbarbosa1979** [Hakame-kun/uBlock-Filters-Indonesia#31]
### Basic information

**Check the link/s:** `https://bitlinks.pw/sh/GR8tlAbXI9m`
**Category:** anti-adblock
**Reported from:** US

### User environment
**Browser:** Chrome 81.0.4044.129 and Firefox 75.0
**Extension or program:** Nano Adblocker v1.0.0.142
**Filter lists:**  Default, uBlock Indo

**Comment by Hakame-kun** [comment]
7da3c40
![image](https://user-images.githubusercontent.com/37291660/81658849-59f31f00-9463-11ea-91a2-9072ff85635b.png)

If brave ads blocked, you will not pass the shortlink. Let me know if this working for you

**Comment by Hakame-kun** [comment]
Edit: 7da3c40

![image](https://user-images.githubusercontent.com/37291660/81658849-59f31f00-9463-11ea-91a2-9072ff85635b.png)

If brave ads blocked, you will not pass the shortlink. Let me know if this works for you

**Comment by Hakame-kun** [comment]
Edit: 41ebbac

![image](https://user-images.githubusercontent.com/37291660/81658849-59f31f00-9463-11ea-91a2-9072ff85635b.png)

If brave ads blocked, you will not pass the shortlink. Let me know if this works for you

**Comment by arbarbosa1979** [comment]
Thank you, this work!
