### ISSUE TITLE
itunesku.com [Anti-AdBlock]

### ISSUE THREAD

**Issue by exodius48** [Hakame-kun/uBlock-Filters-Indonesia#32]
`https://www2.itunesku.com/` terdeteksi sebagai adblock 
=>> https://github.com/uBlockOrigin/uAssets/issues/7729

**Comment by bug-rules** [comment]
Fixed 7 months ago: `@@pagead2.googlesyndication.com/pagead/js/adsbygoogle.js`

https://github.com/Hakame-kun/uBlock-Filters-Indonesia/blob/06ec5d8fa285d3e6cdfb979a781e17959a35e7f7/uBlock%20Indo/ubindo.txt#L786

I just need to add an exception to the script for my side.

---

problematic is `@@jsdelivr.net`

`https://cdn.jsdelivr.net/gh/Arlina-Design/quasar@master/arlinablock.js`

when allow Google no help.

---


Also you can try:

`###arlinablock` 

- pop-up may no break site

`||cdn.jsdelivr.net/gh/arlina-design/quasar@master/arlinablock.js$script,important`

- uAssets recommend block file, `important` ignore problematic ` @@jsdelivr.net`.

**Comment by Hakame-kun** [comment]
> `https://www2.itunesku.com/` terdeteksi sebagai adblock
> =>> [uBlockOrigin/uAssets#7729](https://github.com/uBlockOrigin/uAssets/issues/7729)

![image](https://user-images.githubusercontent.com/37291660/90312329-c0d61780-df2d-11ea-805b-b12d429b1890.png)
Justru tidak bermasalah, apakah agan pakai filter lain ? Kalau iya tolong dicek terlebih dahulu

![image](https://user-images.githubusercontent.com/37291660/90312338-dd724f80-df2d-11ea-8e4f-3806f0adb126.png)
Ini bisa saya akses kok pakai filter uBlock Indo

**Comment by Hakame-kun** [comment]
> `https://www2.itunesku.com/` terdeteksi sebagai adblock
> =>> [uBlockOrigin/uAssets#7729](https://github.com/uBlockOrigin/uAssets/issues/7729)

> `https://www2.itunesku.com/` terdeteksi sebagai adblock
> =>> [uBlockOrigin/uAssets#7729](https://github.com/uBlockOrigin/uAssets/issues/7729)

![image](https://user-images.githubusercontent.com/37291660/90312329-c0d61780-df2d-11ea-805b-b12d429b1890.png)
Justru tidak bermasalah, apakah agan pakai filter lain ? Kalau iya tolong dicek terlebih dahulu

![image](https://user-images.githubusercontent.com/37291660/90312338-dd724f80-df2d-11ea-8e4f-3806f0adb126.png)
Ini bisa saya akses kok pakai filter uBlock Indo

Kalau masih bermasalah silahkan lakukan 'manual update' filter uBlock Indonya. Pastikan tanggalnya sesuai dengan update terakhir yang ada di GitHub dan juga silahkan lihat website uBlock Indo, disitu sudah dituliskan filter apa saja yang cocok dan tidak bermasalah apabila uBlock Indo sudah terinstall di uBlock Origin

Ini filter yang sering saya pakai, 'My Filters' dihitung sebagai 'uBlock Indo' karena mudah untuk saya mengedit filter uBlock Indo
![image](https://user-images.githubusercontent.com/37291660/90312418-83be5500-df2e-11ea-8221-7ccf866029c5.png)

**Comment by exodius48** [comment]
@Hakame-kun 
![2020-08-17_145416](https://user-images.githubusercontent.com/9832875/90371734-999c5900-e099-11ea-8009-86a67c4e1449.png)
![2020-08-17_145433](https://user-images.githubusercontent.com/9832875/90371743-9acd8600-e099-11ea-8576-5c1604afa888.png)

Itu settingan ane gan. Apakah ada yg bentrok? Semua sudah uptodate

**Comment by Hakame-kun** [comment]
Kalau saya pikir, iya kemungkinan bentrokan. Terlalu banyak filter tidak bagus juga, seperlunya saja

Cara cari filter yang bermasalah, buka Logger dulu, terus ubah jadi 'All'
![image](https://user-images.githubusercontent.com/37291660/90464011-91462b80-e136-11ea-8317-1b579a8520de.png)
![image](https://user-images.githubusercontent.com/37291660/90464042-a622bf00-e136-11ea-90c8-f7b16616a7ff.png)

Lihat jsdelivr.net-nya dan lihat diblok sama filter apa, kalau filter saya tidak ngeblok 'jsdelivr.net'. Karena itu CDN, jadi saya pikir diperlukan untuk semua web, so tidak dimasukkan ke blacklist/block
![image](https://user-images.githubusercontent.com/37291660/90464193-f7cb4980-e136-11ea-8b65-9c6855799f72.png)

**Comment by exodius48** [comment]
@Hakame-kun Sudah solved, reset ke default lalu aktifkan Ublock-Indo
