### ISSUE TITLE
Ada iklan di sini

### ISSUE THREAD

**Issue by Jokopentil** [Hakame-kun/uBlock-Filters-Indonesia#37]
![20230120_202207_rmscr.jpg](https://user-images.githubusercontent.com/114223791/213712675-d4f56a31-5d5d-4aee-af79-dac592980111.jpg)![20230120_202524_rmscr.jpg](https://user-images.githubusercontent.com/114223791/213712600-01bc81f2-b9fa-4cd6-92c3-b5fc6ca56c41.jpg)![20230120_204238_rmscr.jpg](https://user-images.githubusercontent.com/114223791/213712970-2549f1bf-aa39-4dc5-9612-4f507c4ffa4a.jpg)![20230120_204403_rmscr.jpg](https://user-images.githubusercontent.com/114223791/213713027-4b9e9073-fd83-4e3b-9b9f-93c17afd771d.jpg)
http://144.126.148.112/terbit21/
http://144.126.148.112/terbit21/
Orami.co.id

**Comment by Hakame-kun** [comment]
[2fb09f3](https://github.com/Hakame-kun/uBlock-Filters-Indonesia/commit/2fb09f38ff7d98140bdd1cdea9ccf406f40ca8e0) Silahkan diupdate ya kak filternya dan dicoba lagi :)

**Comment by Jokopentil** [comment]
Maaf belum hilang setelah di refresh
Iklan baru hilang dengan abpindo dan adblock id

**Comment by Hakame-kun** [comment]
Karena ini bukan filter yang ditambahkan ke uBlock (Non Official filter) jadi perlu manual update kak https://ublockfiltersindonesia.blogspot.com/2018/04/ubindo.html (Scroll sampai bawah, di **Tambahan** ada tutorialnya :+1: )

**Comment by Jokopentil** [comment]
Saya udah subscribe di sini kakak
![20230124_091625_rmscr.jpg](https://user-images.githubusercontent.com/114223791/214199400-22c22dfa-50c5-49fe-86d8-f2d9e85d146b.jpg)

Apakah itu artinya saya harus pasang filter txt di filter saya?

**Comment by Hakame-kun** [comment]
Tidak harus dipasang lagi kak di filter saya, hanya perlu manual update aja kok kak. Jadi hanya perlu ke filter list, cari uBlock Indo (biasanya di Custom atau paling bawah) lalu ikuti tutorial dibawah kak.

![image](https://user-images.githubusercontent.com/37291660/214281053-d03aa1b2-1858-4a19-a5d0-2f7325a7c9fb.png)


Cara mengupdate filters secara manual dapat dilakukan dengan membuka dashboard uBlock Origin, lalu buka Filter lists dan ikuti tutorial di bawah ini.

![image](https://user-images.githubusercontent.com/37291660/214280249-c04df070-e3b6-4b7d-bdac-2c2d975abcd5.png)


Pertama, klik yang bergambar jam/waktu.

Kedua, setelah itu akan berubah menjadi tanda warning/peringatan. Artinya sudah bisa diupdate.

Ketiga, klik Update now dan tunggu beberapa saat agar filternya selesai terupdate.

**Comment by Jokopentil** [comment]
Sudah berhasil, trimakasih
Nanti jika ada iklan boleh lapor lagi

**Comment by Hakame-kun** [comment]
Sama-sama kak, silahkan lapor kembali apabila kakak menemukan website yang iklannya menggangu :+1:
