### ISSUE TITLE
Muncul iklan di sini

### ISSUE THREAD

**Issue by Jokopentil** [Hakame-kun/uBlock-Filters-Indonesia#38]
![20230126_160437_rmscr.jpg](https://user-images.githubusercontent.com/114223791/214847926-be468482-9237-4407-9c14-571d9a1dafb2.jpg)

![20230126_162911_rmscr.jpg](https://user-images.githubusercontent.com/114223791/214848139-fcf6cd14-cdfc-4811-8056-4c9113d6245b.jpg)

![20230126_162336_rmscr.jpg](https://user-images.githubusercontent.com/114223791/214848334-9e5cb4a7-4f94-4ee6-869f-71e67295e97a.jpg)

**Comment by Hakame-kun** [comment]
[fbbd442](https://github.com/Hakame-kun/uBlock-Filters-Indonesia/commit/fbbd442a376ddb2c4c4e33bfe252b4a8d34afab1) Sudah ya kak, silahkan manual update dan dicoba kembali. Oiya kalau bisa jangan lupa cantumkan URL/alamat linknya ya :+1:

**Comment by Jokopentil** [comment]
Ya trimaksi atas respon dan bantuannya🙏🙏
