### ISSUE TITLE
Dimanakah saya dapat belajar kode filter?

### ISSUE THREAD

**Issue by Scavengerz46** [Hakame-kun/uBlock-Filters-Indonesia#40]
seperti ##+js(aopr, adblock) dll

**Comment by Hakame-kun** [comment]
Bisa dibuka di ekstensi uBlocknya ya kak, lalu klik gambar mata di uBlock filters

![image](https://user-images.githubusercontent.com/37291660/232235685-52db4f2e-f71b-4e64-95ab-0f2849886ee9.png)

Banyak sekali disitu, bisa dicoba satu persatu di website yang ingin kakak coba. Apabila cocok misalnya di website tersebut ada anti-adblock, akan hilang jika berhasil

**Comment by Hakame-kun** [comment]
Bisa dibuka di ekstensi uBlocknya ya kak, lalu klik gambar mata di uBlock filters

![image](https://user-images.githubusercontent.com/37291660/232235783-8ed3206a-f906-475d-85a1-fbe2d643b3c8.png)

Banyak sekali disitu, bisa dicoba satu persatu di website yang ingin kakak coba. Apabila cocok misalnya di website tersebut ada anti-adblock, akan hilang jika berhasil

**Comment by SungTaehon** [comment]
> Bisa dibuka di ekstensi uBlocknya ya kak, lalu klik gambar mata di uBlock filter
> 
> ![gambar](https://user-images.githubusercontent.com/37291660/232235783-8ed3206a-f906-475d-85a1-fbe2d643b3c8.png)
> 
> Banyak sekali disitu, bisa dicoba satu bersama di website yang ingin kakak coba. Apabila cocok misalnya di website tersebut ada anti adblock, akan hilang jika berhasil

ada channel telegram apa grup diskusi kah kak?
