### ISSUE TITLE
https://45.141.56.28/800-bullets-2002-jf/

### ISSUE THREAD

**Issue by Jokopentil** [Hakame-kun/uBlock-Filters-Indonesia#41]
Banner link iklan vidio jika di klik![20230701_082235_rmscr.jpg](https://github.com/Hakame-kun/uBlock-Filters-Indonesia/assets/114223791/1385ee30-685c-4005-8768-afa13c243014)
Yg di bawah ini screenshoot yg setelah skip dan tak ada iklan
![20230701_082640_rmscr.jpg](https://github.com/Hakame-kun/uBlock-Filters-Indonesia/assets/114223791/a071b5f6-eec5-4171-b511-39b3975ac5d8)

**Comment by Hakame-kun** [comment]
Silahkan diupdate dan dicoba lagi kak 👍
